#!/bin/bash

destination="$(date +'%m-%d-%Y')"
write="./logs/$destination"
if [ -z "$(git status --porcelain)" ]; then
	echo "No changes to commit." >> "$write".txt
	echo -e "Checked for changes at $(date)\n" >> "$write".txt
	git add .
	git commit -m "Log modification before proper update"
	git push origin --progress

else
	echo -e "Changes were found on $(date)\n" >> "$write".txt
	git add .
	git commit -m "Modifications for $destination"
	git push origin  --progress
fi
