#!/bin/bash

destination="$(date +'%m-%d-%Y')"
write="./logs/$destination"
if [ -z "$(git status --porcelain)" ]; then
	echo "No changes to commit."
	echo "Checked for changes at $(date)" >> "./logs/$destination".txt
	add=$( (git add .) 2>&1)
	commit=$( (git commit -m "Log modification before proper update") 2>&1)
	push=$( (git push origin --progress) 2>&1)

	echo "Adding the changed files to git\n"
	echo "$add" >> "./logs/$destination".txt
	echo "Commiting the changes to git\n"
	echo "$commit" >> "./logs/$destination".txt
	echo "Pushing to the repository\n"
	echo "$push" >> "./logs/$destination".txt
else
	add=$( (git add .) 2>&1)
	commit=$( (git commit -m "Modifications for $destination") 2>&1)
	push=$( (git push origin  --progress) 2>&1)

	# echo "var = $var"
	# echo "end of var"


	echo "Adding the changed files to git\n" >> "$write".txt
	echo "$add" >> "./logs/$destination".txt
	echo "Commiting the changes to git\n"
	echo "$commit" >> "./logs/$destination".txt
	echo "Pushing to the repository\n"
	echo "$push" >> "./logs/$destination".txt

fi
